config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  # Magic link sign in/up/out and session management
  get 'welcome' => 'sessions#new', as: :sessions_new
  post 'sessions/create' => 'sessions#create', as: :sessions_create
  get 'magic/email' => 'sessions#email', as: :sessions_email
  get 'magic/link' => 'sessions#verify', as: :sessions_verify
  get 'sign-out' => 'sessions#destroy', as: :sessions_destroy
  get 'session/test' => 'sessions#test', as: :sessions_test

  mount Debugbar::Engine => Debugbar.config.prefix if defined? Debugbar
end

app/models/application_record.rb
# frozen_string_literal: true

# Base class for all models
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  # Automatically strip spaces from email
  auto_strip_attributes :email

  # Lowercase emails before validating
  before_validation { email&.downcase! }

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base level controller for everything
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def sign_in_user(user_id)
    # Issue a new session identifier after successful login
    # See: https://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session

    session[:user_id] = user_id
    extend_session
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    if session[:valid_until].present? && (session[:valid_until] > Time.now.utc.to_i) && current_user
      extend_session
      return
    end

    # Expired or invalid session
    reset_session # TODO: Figure out if I want to do this or not - its a security meausre
    redirect_to sessions_new_path
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def extend_session
    session[:valid_until] = 30.days.from_now.utc.to_i
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for home page
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  # GET /
  def index; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Handles user authentication session management
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, except: [:test]
  before_action :set_new_user, only: [:create]

  def new
    @user = User.new
  end

  def create
    # Validate email address
    return render :new, status: :unprocessable_entity unless @user.valid?

    # Send magic link email
    magic_link_url = sessions_verify_url(token: MagicLink.generate_token(@user.email))
    UserMailer.with(email: @user.email, url: magic_link_url).magic_link_email.deliver_later
    session[:unverified_email] = session_params[:email]
    redirect_to sessions_email_path
  end

  def email
    redirect_to root_url if user_signed_in?
    @unverified_email = session[:unverified_email]
  end

  def verify # rubocop:disable Metrics/AbcSize
    email = MagicLink.verify_token(params[:token])
    if email
      user = User.find_or_create_by(email:)
      sign_in_user(user.id)
      flash[:notice] = t('.signed_in_as', email: user.email)
      redirect_to root_url
    else
      flash[:error] = t('.invalid_magic_link')
      redirect_to sessions_new_path
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  def test
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:email)
  end

  def set_new_user
    @user = User.build(session_params)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Custom helper methods used (mostly) in views
module ApplicationHelper
  def form_error_notification(object)
    return unless object.errors.any?

    tag.div class: 'error-message text-red-600 dark:text-red-400' do
      object.errors.full_messages.to_sentence.capitalize
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Custom helper methods used (mostly) in views for the Home controller.
module HomeHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# Custom helper methods for sessions.
module SessionsHelper
end

app/views/home/index.html.erb
<div class="font-bold">Hello!</div>

<% if !user_signed_in? %>
  <%= link_to 'Get in here', sessions_new_path %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="bg-slate-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">

      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <%= link_to image_tag("https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500", alt: 'Logo', class: 'h-8 w-auto'), root_path %>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 space-x-4 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

        <!-- Dark mode toggle button -->
        <button type="button" aria-label="Dark mode toggle" data-controller="dark-mode" data-action="click->dark-mode#toggleMode">
          <span class="dark:hidden">
            <svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-6 h-6">
              <path d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" class="stroke-slate-400 dark:stroke-slate-500"></path>
              <path d="M12 4v1M17.66 6.344l-.828.828M20.005 12.004h-1M17.66 17.664l-.828-.828M12 20.01V19M6.34 17.664l.835-.836M3.995 12.004h1.01M6 6l.835.836" class="stroke-slate-400 dark:stroke-slate-500"></path>
            </svg>
          </span>
          <span class="hidden dark:inline">
            <svg viewBox="0 0 24 24" fill="none" class="w-6 h-6">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M17.715 15.15A6.5 6.5 0 0 1 9 6.035C6.106 6.922 4 9.645 4 12.867c0 3.94 3.153 7.136 7.042 7.136 3.101 0 5.734-2.032 6.673-4.853Z" class="fill-transparent"></path>
              <path d="m17.715 15.15.95.316a1 1 0 0 0-1.445-1.185l.495.869ZM9 6.035l.846.534a1 1 0 0 0-1.14-1.49L9 6.035Zm8.221 8.246a5.47 5.47 0 0 1-2.72.718v2a7.47 7.47 0 0 0 3.71-.98l-.99-1.738Zm-2.72.718A5.5 5.5 0 0 1 9 9.5H7a7.5 7.5 0 0 0 7.5 7.5v-2ZM9 9.5c0-1.079.31-2.082.845-2.93L8.153 5.5A7.47 7.47 0 0 0 7 9.5h2Zm-4 3.368C5 10.089 6.815 7.75 9.292 6.99L8.706 5.08C5.397 6.094 3 9.201 3 12.867h2Zm6.042 6.136C7.718 19.003 5 16.268 5 12.867H3c0 4.48 3.588 8.136 8.042 8.136v-2Zm5.725-4.17c-.81 2.433-3.074 4.17-5.725 4.17v2c3.552 0 6.553-2.327 7.622-5.537l-1.897-.632Z" class="fill-slate-400 dark:fill-slate-500"></path>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M17 3a1 1 0 0 1 1 1 2 2 0 0 0 2 2 1 1 0 1 1 0 2 2 2 0 0 0-2 2 1 1 0 1 1-2 0 2 2 0 0 0-2-2 1 1 0 1 1 0-2 2 2 0 0 0 2-2 1 1 0 0 1 1-1Z" class="fill-slate-400 dark:fill-slate-500"></path>
            </svg>
          </span>
        </button>

        <% if user_signed_in? %>
          <%= link_to t('sessions.sign_out'), sessions_destroy_path, class: 'text-slate-50' %>
        <% else %>
          <%= link_to t('sessions.sign_in'), sessions_new_path, class: 'text-slate-50' %>
        <% end %>
      </div>
    </div>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-slate-50 dark:bg-slate-900">
  <head>
    <title>Rails Base</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full text-slate-900 dark:text-slate-50">
    <%= render "layouts/nav" %>
    <main class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
      <%= yield %>
    </main>

    <% if defined? Debugbar %>
      <%= debugbar_javascript %>
    <% end %>
  </body>
</html>